import type { Product, Category } from '@/types'

export const CATEGORIES: Category[] = [
  { slug: 'face-tissue',    name: 'مناديل الوجه',      nameEn: 'Face Tissue',     icon: '🧻' },
  { slug: 'wet-wipes',      name: 'مناديل مبللة',       nameEn: 'Wet Wipes',       icon: '💧' },
  { slug: 'cotton-towels',  name: 'مناشف قطنية',       nameEn: 'Cotton Towels',   icon: '🏠' },
  { slug: 'kitchen',        name: 'مناشف المطبخ',       nameEn: 'Kitchen Towels',  icon: '🍽️' },
  { slug: 'pocket',         name: 'مناديل الجيب',      nameEn: 'Pocket Tissue',   icon: '🧳' },
  { slug: 'specialty',      name: 'منتجات خاصة',       nameEn: 'Specialty',       icon: '✨' },
  { slug: 'bundles',        name: 'بكجات التوفير',     nameEn: 'Bundles',         icon: '🎁' },
]

const IMG = [
  'https://images.unsplash.com/photo-1609840112990-4265448268d1?w=600&q=80', // tissue box blue
  'https://images.unsplash.com/photo-1584651772793-d555266cce99?w=600&q=80', // tissue box on desk
  'https://images.unsplash.com/photo-1607516531499-9e57ef94a9d9?w=600&q=80', // floral tissue box
  'https://images.unsplash.com/photo-1746351635660-67a0c51f5c6f?w=600&q=80', // 3D tissue box
  'https://images.unsplash.com/photo-1598046937985-11c320dfd379?w=600&q=80', // tissue roll white
  'https://images.unsplash.com/photo-1585690359409-9020f3602bdb?w=600&q=80', // multiple paper rolls
  'https://images.unsplash.com/photo-1583496597467-d968d2fa33a8?w=600&q=80', // toilet paper white table
  'https://images.unsplash.com/photo-1584109807991-ebfcd80112a8?w=600&q=80', // tissue roll blue bg
  'https://images.unsplash.com/photo-1584743578805-d7991ca2d5d4?w=600&q=80', // wipes/tissues pack
  'https://images.unsplash.com/photo-1620778864482-5f20e3d9745a?w=600&q=80', // paper roll texture
  'https://images.unsplash.com/photo-1708337338728-9fe34ccb91b4?w=600&q=80', // tissue dispenser
  'https://images.unsplash.com/photo-1734599395438-1ec2a861ed8d?w=600&q=80', // organic wipes
]

const img = (i: number) => IMG[i % IMG.length]
const imgs = (i: number) => [img(i), img(i + 2), img(i + 4)]

const CAT = (slug: string) => CATEGORIES.find(c => c.slug === slug)!

export const PRODUCTS: Product[] = [
  /* ===================== FACE TISSUE (22) ===================== */
  {
    id: 1, slug: 'nada-classic-600',
    name: 'مناديل NOVI كلاسيك — ٦٠٠ منديل', nameEn: 'NOVI Classic 600',
    category: CAT('face-tissue'), price: 29.99, comparePrice: 39.99,
    rating: 4.9, reviewCount: 842, stock: 500, sold: 12400, sku: 'ND-FT-001',
    badge: { label: 'الأكثر مبيعاً', color: 'gold' },
    images: imgs(0), tags: ['مناديل', 'كلاسيك'],
    description: 'مناديل NOVI كلاسيك الفاخرة بـ٣ طبقات من الألياف الطبيعية النقية. ٦٠٠ منديل في كل علبة — أكثر من المنافسين. نعومة استثنائية تشعر بها من أول لمسة، ولطيفة جداً على البشرة الحساسة والأطفال.',
    features: ['٣ طبقات فاخرة ناعمة', '٦٠٠ منديل في كل علبة', 'مواد طبيعية ١٠٠٪', 'معتمدة من هيئة الغذاء والدواء السعودية', 'لطيفة على البشرة الحساسة', 'متاحة بلون وردي وأخضر'],
    specs: { 'العدد': '٦٠٠ منديل', 'الطبقات': '٣', 'الحجم': '٢١×٢١ سم', 'الوزن': '٥٨٠ جم', 'اللون': 'وردي / أخضر', 'SKU': 'ND-FT-001' },
    isBestSeller: true, isFeatured: true,
  },
  {
    id: 2, slug: 'nada-ultra-soft-600',
    name: 'مناديل NOVI الترا سوفت — ٦٠٠', nameEn: 'Ultra Soft 600',
    category: CAT('face-tissue'), price: 34.99, comparePrice: 44.99,
    rating: 4.8, reviewCount: 634, stock: 380, sold: 9800, sku: 'ND-FT-002',
    badge: { label: 'جديد', color: 'blue' },
    images: imgs(1), tags: ['مناديل', 'فائقة النعومة'],
    description: 'مناديل ترا سوفت الجديدة بتركيبة فائقة النعومة من ٤ طبقات. تقنية الألياف المائية تجعلها أكثر نعومة وامتصاصاً من أي مناديل أخرى في السوق.',
    features: ['٤ طبقات فائقة النعومة', 'تقنية الألياف المائية', 'بدون عطور أو كيماويات', '٦٠٠ منديل', 'آمنة للبشرة الحساسة جداً', 'مقاومة للتفتت حتى مبللة'],
    specs: { 'العدد': '٦٠٠ منديل', 'الطبقات': '٤', 'الحجم': '٢١×٢٢ سم', 'الوزن': '٦٢٠ جم' },
    isNew: true,
  },
  {
    id: 3, slug: 'nada-maxi-1800',
    name: 'مناديل NOVI ماكسي — ١٨٠٠ منديل', nameEn: 'NOVI Maxi 1800',
    category: CAT('face-tissue'), price: 64.99, comparePrice: 89.99,
    rating: 4.9, reviewCount: 521, stock: 200, sold: 7200, sku: 'ND-FT-003',
    badge: { label: 'وفّر ٢٨٪', color: 'red' },
    images: imgs(2), tags: ['مناديل', 'ماكسي', 'كبير'],
    description: 'أكبر علبة مناديل في المملكة! ١٨٠٠ منديل بـ٥ طبقات فاخرة. تدوم ٣ أضعاف العلبة العادية. تأتي مع ٣ علاقات مجانية. حصرية في متجر NOVI.',
    features: ['١٨٠٠ منديل ضخمة', '٥ طبقات سميكة', '٣ علاقات مجانية مضمنة', 'الأطول دواماً في المملكة', 'حصرية في NOVI'],
    specs: { 'العدد': '١٨٠٠ منديل', 'الطبقات': '٥', 'الحجم': '٢٣×٢٣ سم', 'الوزن': '١.٨ كجم' },
    isFeatured: true, isBestSeller: true,
  },
  {
    id: 4, slug: 'nada-classic-400',
    name: 'مناديل NOVI كلاسيك — ٤٠٠ منديل', nameEn: 'Classic 400',
    category: CAT('face-tissue'), price: 21.99, comparePrice: 27.99,
    rating: 4.7, reviewCount: 389, stock: 600, sold: 8900, sku: 'ND-FT-004',
    images: imgs(3), tags: ['مناديل', 'متوسط'],
    description: 'مناديل كلاسيك حجم متوسط مثالية للغرف والمكاتب. ٤٠٠ منديل بـ٣ طبقات ناعمة. السعر المناسب مع الجودة التي تستحقها.',
    features: ['٤٠٠ منديل', '٣ طبقات', 'حجم مثالي للمكتب', 'تصميم أنيق', 'ألوان متعددة متاحة'],
    specs: { 'العدد': '٤٠٠ منديل', 'الطبقات': '٣', 'الحجم': '٢٠×٢٠ سم' },
  },
  {
    id: 5, slug: 'nada-premium-white',
    name: 'مناديل NOVI بريميوم وايت — ٦٠٠', nameEn: 'Premium White 600',
    category: CAT('face-tissue'), price: 37.99, comparePrice: 49.99,
    rating: 4.8, reviewCount: 445, stock: 320, sold: 6700, sku: 'ND-FT-005',
    badge: { label: 'مميز', color: 'gold' },
    images: imgs(4), tags: ['مناديل', 'أبيض', 'فاخر'],
    description: 'مناديل بيضاء فاخرة بتقنية التبييض الطبيعي بدون كلور. ناصعة البياض، فائقة النعومة. تختلف تماماً عن أي مناديل بيضاء أخرى في السوق.',
    features: ['بياض طبيعي بدون كلور', '٦٠٠ منديل', '٣ طبقات مضغوطة', 'بدون عطور', 'آمنة بيئياً ومعتمدة'],
    specs: { 'العدد': '٦٠٠ منديل', 'الطبقات': '٣', 'اللون': 'أبيض ناصع طبيعي' },
  },
  {
    id: 6, slug: 'nada-aloe-vera-600',
    name: 'مناديل NOVI بالصبار — ٦٠٠ منديل', nameEn: 'Aloe Vera 600',
    category: CAT('face-tissue'), price: 39.99, comparePrice: 52.99,
    rating: 4.9, reviewCount: 612, stock: 280, sold: 9100, sku: 'ND-FT-006',
    badge: { label: 'الأكثر مبيعاً', color: 'gold' },
    images: imgs(5), tags: ['مناديل', 'صبار', 'ترطيب'],
    description: 'مناديل مدعمة بخلاصة الصبار الطبيعية. تغذي البشرة وترطبها مع كل استخدام. مثالية للبشرة الجافة والحساسة التي تحتاج عناية خاصة.',
    features: ['مدعمة بخلاصة صبار ٢٠٪', 'ترطيب فوري للبشرة', 'بدون كحول', 'آمنة للبشرة الحساسة جداً', '٦٠٠ منديل بـ٣ طبقات'],
    specs: { 'العدد': '٦٠٠ منديل', 'المكونات النشطة': 'خلاصة صبار ٢٠٪', 'الطبقات': '٣' },
    isBestSeller: true,
  },
  {
    id: 7, slug: 'nada-sensitive-skin',
    name: 'مناديل NOVI للبشرة الحساسة — ٦٠٠', nameEn: 'Sensitive Skin 600',
    category: CAT('face-tissue'), price: 41.99, comparePrice: 54.99,
    rating: 4.9, reviewCount: 778, stock: 350, sold: 11200, sku: 'ND-FT-007',
    badge: { label: 'موصى به طبياً', color: 'green' },
    images: imgs(6), tags: ['مناديل', 'حساسة', 'طبي'],
    description: 'مناديل خصيصاً للبشرة الحساسة والمهيجة. مختبرة ومعتمدة جلدياً من كبرى المختبرات الأوروبية. بدون عطور أو مواد مسرطنة.',
    features: ['معتمدة جلدياً ١٠٠٪', 'بدون عطور أو صبغات', 'بدون كحول أو بارابين', 'اختبار حساسية صفري', 'مناسبة لمرضى الأكزيما والصدفية'],
    specs: { 'العدد': '٦٠٠ منديل', 'الاعتمادات': 'SFDA، Allergy UK، ISO', 'الطبقات': '٤' },
    isFeatured: true,
  },
  {
    id: 8, slug: 'nada-lavender-500',
    name: 'مناديل NOVI برائحة اللافندر — ٥٠٠', nameEn: 'Lavender 500',
    category: CAT('face-tissue'), price: 32.99, comparePrice: 41.99,
    rating: 4.6, reviewCount: 234, stock: 420, sold: 4500, sku: 'ND-FT-008',
    badge: { label: 'جديد', color: 'blue' },
    images: imgs(7), tags: ['مناديل', 'معطر', 'لافندر'],
    description: 'مناديل معطرة برائحة اللافندر الهادئة المريحة. تملأ غرفتك بعطر رائع مع كل استخدام. مستوحاة من حقول اللافندر الفرنسية.',
    features: ['عطر لافندر طبيعي', '٥٠٠ منديل', '٣ طبقات', 'ليست قوية على الجهاز التنفسي', 'تصميم أرجواني جميل'],
    specs: { 'العدد': '٥٠٠ منديل', 'العطر': 'لافندر طبيعي', 'الطبقات': '٣' },
    isNew: true,
  },
  {
    id: 9, slug: 'nada-economy-600',
    name: 'مناديل NOVI اقتصادية — ٦٠٠ منديل', nameEn: 'Economy 600',
    category: CAT('face-tissue'), price: 17.99,
    rating: 4.4, reviewCount: 156, stock: 800, sold: 6700, sku: 'ND-FT-009',
    images: imgs(0), tags: ['مناديل', 'اقتصادي', 'مكتب'],
    description: 'مناديل اقتصادية بجودة مقبولة وسعر مناسب للجميع. مثالية للاستخدام اليومي الكثيف في المكاتب والمستشفيات.',
    features: ['سعر مناسب للجميع', '٦٠٠ منديل', 'طبقتان متينتان', 'مثالية للمكاتب الكبيرة', 'كميات جملة متاحة'],
    specs: { 'العدد': '٦٠٠ منديل', 'الطبقات': '٢', 'الحجم': '١٩×١٩ سم' },
  },
  {
    id: 10, slug: 'nada-designer-blue',
    name: 'مناديل NOVI ديزاينر — تصميم أزرق', nameEn: 'Designer Blue',
    category: CAT('face-tissue'), price: 44.99, comparePrice: 55.99,
    rating: 4.7, reviewCount: 198, stock: 150, sold: 2800, sku: 'ND-FT-010',
    badge: { label: 'جديد', color: 'blue' },
    images: imgs(1), tags: ['مناديل', 'ديزاينر', 'هدية'],
    description: 'مناديل فاخرة في علبة ديزاينر زرقاء أنيقة. تزين أي طاولة وتعكس ذوقك الراقي. مثالية كهدية في المناسبات.',
    features: ['علبة ديزاينر فاخرة', '٥٠٠ منديل', '٤ طبقات', 'تصميم حصري', 'هدية مثالية للمناسبات'],
    specs: { 'العدد': '٥٠٠ منديل', 'الطبقات': '٤', 'التصميم': 'ديزاينر أزرق فاخر' },
    isNew: true,
  },
  {
    id: 11, slug: 'nada-ultra-thick-300',
    name: 'مناديل NOVI الثقيلة — ٣٠٠ منديل', nameEn: 'Ultra Thick 300',
    category: CAT('face-tissue'), price: 36.99, comparePrice: 46.99,
    rating: 4.8, reviewCount: 312, stock: 270, sold: 5100, sku: 'ND-FT-011',
    images: imgs(2), tags: ['مناديل', 'سميك', 'قوي'],
    description: 'مناديل بـ٦ طبقات ثقيلة جداً. كل منديل يكفي وحده ويعادل ٣ مناديل عادية. مثالية للرياضيين والمسافرين.',
    features: ['٦ طبقات سميكة', 'كل منديل يعادل ٣ مناديل', 'لا تتفتت حتى مبللة', 'مثالية للرياضة', '٣٠٠ منديل'],
    specs: { 'العدد': '٣٠٠ منديل', 'الطبقات': '٦', 'السماكة': '٠.٨ مم' },
  },
  {
    id: 12, slug: 'nada-kids-cartoon',
    name: 'مناديل NOVI للأطفال — رسوم كرتونية', nameEn: 'Kids Cartoon',
    category: CAT('face-tissue'), price: 27.99, comparePrice: 34.99,
    rating: 4.8, reviewCount: 489, stock: 430, sold: 7800, sku: 'ND-FT-012',
    badge: { label: 'الأطفال يحبونه', color: 'gold' },
    images: imgs(3), tags: ['مناديل', 'أطفال', 'كرتون'],
    description: 'مناديل مزينة برسوم كرتونية محببة للأطفال. تجعلهم يحبون استخدام المناديل. آمنة ١٠٠٪ من يوم الولادة.',
    features: ['رسوم كرتونية ملونة محببة', 'آمنة للأطفال من ٠ سنة', 'بدون كيماويات ضارة', 'لطيفة على بشرة الأطفال', '٥٠٠ منديل بـ٣ طبقات'],
    specs: { 'العدد': '٥٠٠ منديل', 'عمر الاستخدام': 'من ٠ سنة', 'الطبقات': '٣' },
  },
  {
    id: 13, slug: 'nada-bamboo-600',
    name: 'مناديل NOVI بامبو — ٦٠٠ منديل', nameEn: 'Bamboo 600',
    category: CAT('face-tissue'), price: 49.99, comparePrice: 64.99,
    rating: 4.9, reviewCount: 267, stock: 180, sold: 3900, sku: 'ND-FT-013',
    badge: { label: 'صديق للبيئة', color: 'green' },
    images: imgs(4), tags: ['مناديل', 'بامبو', 'بيئة'],
    description: 'مناديل مصنوعة من ألياف الخيزران الطبيعية. أسرع تحللاً وأكثر استدامة للبيئة. نعومة طبيعية فائقة تشعر بها.',
    features: ['ألياف خيزران طبيعية ١٠٠٪', 'صديق للبيئة قابل للتحلل', 'أكثر نعومة من القطن العادي', 'ضد البكتيريا طبيعياً', 'شهادة FSC'],
    specs: { 'المادة': 'ألياف خيزران ١٠٠٪', 'الشهادة': 'FSC، ISO 14001', 'العدد': '٦٠٠ منديل' },
    isNew: true, isFeatured: true,
  },
  {
    id: 14, slug: 'nada-rose-500',
    name: 'مناديل NOVI برائحة الورد — ٥٠٠', nameEn: 'Rose 500',
    category: CAT('face-tissue'), price: 31.99, comparePrice: 39.99,
    rating: 4.6, reviewCount: 198, stock: 360, sold: 4200, sku: 'ND-FT-014',
    images: imgs(5), tags: ['مناديل', 'ورد', 'معطر'],
    description: 'مناديل معطرة بعطر الورد الجوري الطبيعي. لحظة من الرقي والأناقة مع كل استخدام. هدية مثالية للأحبة.',
    features: ['عطر ورد جوري طبيعي', '٥٠٠ منديل', '٣ طبقات', 'علبة وردية أنيقة', 'هدية مثالية'],
    specs: { 'العطر': 'ورد جوري طبيعي', 'العدد': '٥٠٠ منديل', 'الطبقات': '٣' },
  },
  {
    id: 15, slug: 'nada-vitamin-e-600',
    name: 'مناديل NOVI بفيتامين E — ٦٠٠', nameEn: 'Vitamin E 600',
    category: CAT('face-tissue'), price: 43.99, comparePrice: 55.99,
    rating: 4.8, reviewCount: 341, stock: 210, sold: 5800, sku: 'ND-FT-015',
    badge: { label: 'عناية فائقة', color: 'gold' },
    images: imgs(6), tags: ['مناديل', 'فيتامين', 'عناية'],
    description: 'مناديل مدعمة بفيتامين E المضاد للأكسدة. تحارب الجفاف وتحمي البشرة مع كل استخدام. الاختيار الأمثل لعناية البشرة اليومية.',
    features: ['مدعمة بفيتامين E قوي', 'مضاد للأكسدة', 'يحارب علامات التقدم', '٦٠٠ منديل', '٤ طبقات فاخرة'],
    specs: { 'فيتامين E': '١٥٪', 'العدد': '٦٠٠ منديل', 'الطبقات': '٤' },
  },
  {
    id: 16, slug: 'nada-antibacterial-600',
    name: 'مناديل NOVI مضادة للبكتيريا — ٦٠٠', nameEn: 'Antibacterial 600',
    category: CAT('face-tissue'), price: 46.99, comparePrice: 59.99,
    rating: 4.8, reviewCount: 389, stock: 240, sold: 6800, sku: 'ND-FT-016',
    badge: { label: 'حماية فائقة', color: 'green' },
    images: imgs(7), tags: ['مناديل', 'بكتيريا', 'حماية'],
    description: 'مناديل بتركيبة نانو-فضية مضادة للبكتيريا والفيروسات. تقضي على ٩٩.٩٪ من الجراثيم الضارة.',
    features: ['تقنية نانو فضية', 'تقضي على ٩٩.٩٪ البكتيريا', 'مضادة للفيروسات', '٦٠٠ منديل', 'آمنة للاستخدام اليومي'],
    specs: { 'الفعالية': '٩٩.٩٪ ضد البكتيريا', 'التقنية': 'نانو فضية', 'العدد': '٦٠٠ منديل' },
    isFeatured: true,
  },
  {
    id: 17, slug: 'nada-luxury-5layer',
    name: 'مناديل NOVI لوكشري — ٥ طبقات ٤٠٠', nameEn: 'Luxury 5-Layer 400',
    category: CAT('face-tissue'), price: 58.99, comparePrice: 74.99,
    rating: 4.9, reviewCount: 167, stock: 130, sold: 2300, sku: 'ND-FT-017',
    badge: { label: 'الأفخم', color: 'gold' },
    images: imgs(0), tags: ['مناديل', 'لوكشري', 'فاخر'],
    description: 'أفخم مناديل وجه في المملكة العربية السعودية. ٥ طبقات فائقة السماكة والنعومة. تجربة فريدة لا تُنسى.',
    features: ['٥ طبقات فائقة الجودة', 'أسمك وأنعم منديل', 'ألياف مستوردة ممتازة', 'تجربة فندقية في منزلك', '٤٠٠ منديل'],
    specs: { 'العدد': '٤٠٠ منديل', 'الطبقات': '٥', 'المادة': 'ألياف مستوردة ممتازة' },
    isFeatured: true,
  },
  {
    id: 18, slug: 'nada-gold-box-500',
    name: 'مناديل NOVI علبة ذهبية — ٥٠٠', nameEn: 'Gold Box 500',
    category: CAT('face-tissue'), price: 54.99, comparePrice: 69.99,
    rating: 4.9, reviewCount: 156, stock: 100, sold: 2100, sku: 'ND-FT-018',
    badge: { label: 'فاخر', color: 'gold' },
    images: imgs(1), tags: ['مناديل', 'ذهبي', 'هدية'],
    description: 'العلبة الذهبية الفاخرة — قمة الرقي والفخامة. مناديل ٥ طبقات في علبة ذهبية اللون. الهدية المثالية للمناسبات الراقية.',
    features: ['علبة ذهبية فاخرة حصرية', '٥٠٠ منديل', '٥ طبقات', 'مثالية كهدية فاخرة', 'تصميم حصري'],
    specs: { 'العدد': '٥٠٠ منديل', 'الطبقات': '٥', 'التصميم': 'ذهبي فاخر' },
    isFeatured: true,
  },
  {
    id: 19, slug: 'nada-2pack-600',
    name: 'عبوة ثنائية NOVI — ٢ × ٦٠٠', nameEn: 'Twin Pack 2x600',
    category: CAT('face-tissue'), price: 52.99, comparePrice: 69.98,
    rating: 4.8, reviewCount: 445, stock: 300, sold: 8200, sku: 'ND-FT-019',
    badge: { label: 'وفّر ٢٤٪', color: 'red' },
    images: imgs(2), tags: ['مناديل', 'عبوة', 'توفير'],
    description: 'عبوة ثنائية اقتصادية من مناديل NOVI كلاسيك. علبتان بسعر أقل. اجمع الجودة والتوفير في طلب واحد.',
    features: ['علبتان كلاسيك كاملتان', 'إجمالي ١٢٠٠ منديل', 'توفير ١٧ ريال فعلي', 'نفس الجودة الفاخرة', 'أفضل قيمة للعائلات'],
    specs: { 'العدد': '٢ علبة', 'الإجمالي': '١٢٠٠ منديل', 'الطبقات': '٣' },
  },
  {
    id: 20, slug: 'nada-cube-200',
    name: 'مناديل NOVI كيوب — ٢٠٠ منديل', nameEn: 'Cube Box 200',
    category: CAT('face-tissue'), price: 16.99, comparePrice: 21.99,
    rating: 4.6, reviewCount: 234, stock: 550, sold: 5400, sku: 'ND-FT-020',
    images: imgs(3), tags: ['مناديل', 'كيوب', 'حمام'],
    description: 'علبة مناديل مكعبة صغيرة ومريحة. تناسب طاولة السرير والمكتب الصغير والحمام. شكل عملي أنيق.',
    features: ['شكل مكعب أنيق', '٢٠٠ منديل', '٣ طبقات', 'مناسبة للحمام والسرير', 'ألوان متعددة متاحة'],
    specs: { 'الشكل': 'مكعب ١٢×١٢×١٢ سم', 'العدد': '٢٠٠ منديل', 'الطبقات': '٣' },
  },
  {
    id: 21, slug: 'nada-flat-box-600',
    name: 'مناديل NOVI فلات بوكس — ٦٠٠', nameEn: 'Flat Box 600',
    category: CAT('face-tissue'), price: 33.99, comparePrice: 42.99,
    rating: 4.7, reviewCount: 223, stock: 290, sold: 5600, sku: 'ND-FT-021',
    images: imgs(4), tags: ['مناديل', 'فلات', 'سيارة'],
    description: 'علبة مناديل أفقية مسطحة تناسب طاولات السيارات والمكاتب الصغيرة. تصميم عملي أنيق لا يأخذ مكاناً.',
    features: ['تصميم مسطح أفقي', 'مثالية للسيارة والمكتب', 'علبة قوية لا تنهار', '٦٠٠ منديل', 'ألوان متعددة'],
    specs: { 'القياسات': '٣٠×١٢×٩ سم', 'العدد': '٦٠٠ منديل', 'الطبقات': '٣' },
  },
  {
    id: 22, slug: 'nada-pink-600',
    name: 'مناديل NOVI وردية — ٦٠٠ منديل', nameEn: 'Pink Edition 600',
    category: CAT('face-tissue'), price: 28.99, comparePrice: 36.99,
    rating: 4.6, reviewCount: 178, stock: 450, sold: 6100, sku: 'ND-FT-022',
    images: imgs(5), tags: ['مناديل', 'وردي', 'ديكور'],
    description: 'مناديل وردية اللون لتزيين غرفتك بلمسة من الأنوثة والجمال. نفس الجودة العالية بلون مميز يزين المكان.',
    features: ['لون وردي مميز', '٦٠٠ منديل', '٣ طبقات', 'صبغة آمنة غير سامة', 'لتزيين الغرف بأناقة'],
    specs: { 'اللون': 'وردي فاتح', 'العدد': '٦٠٠ منديل', 'الطبقات': '٣' },
  },

  /* ===================== WET WIPES (16) ===================== */
  {
    id: 23, slug: 'wipe-classic-80',
    name: 'مناديل مبللة نَدى كلاسيك — ٨٠', nameEn: 'Wet Wipes Classic 80',
    category: CAT('wet-wipes'), price: 19.99, comparePrice: 24.99,
    rating: 4.9, reviewCount: 1240, stock: 800, sold: 22000, sku: 'ND-WW-001',
    badge: { label: 'الأكثر مبيعاً', color: 'gold' },
    images: imgs(6), tags: ['مبللة', 'صبار', 'وجه'],
    description: 'مناديل مبللة برائحة الصبار اللطيفة. ٨٠ منديل كبير في كل عبوة. مناسبة للوجه واليدين والجسم. خالية من الكحول.',
    features: ['تركيبة صبار طبيعية ٢٠٪', 'خالية من الكحول والبارابين', 'مناسبة للوجه واليدين', '٨٠ منديل كبير الحجم', 'غطاء محكم الإغلاق'],
    specs: { 'العدد': '٨٠ منديل', 'المكونات': 'صبار، فيتامين E', 'بدون': 'كحول، بارابين' },
    isBestSeller: true, isFeatured: true,
  },
  {
    id: 24, slug: 'wipe-baby-100',
    name: 'مناديل أطفال مبللة نَدى — ١٠٠', nameEn: 'Baby Wipes 100',
    category: CAT('wet-wipes'), price: 22.99, comparePrice: 27.99,
    rating: 5.0, reviewCount: 678, stock: 650, sold: 15400, sku: 'ND-WW-002',
    badge: { label: '⭐ ٥ نجوم', color: 'gold' },
    images: imgs(7), tags: ['مبللة', 'أطفال', 'رضع'],
    description: 'مناديل مبللة فائقة اللطف للأطفال والرضع. مختبرة ومعتمدة جلدياً من كبرى المختبرات. آمنة من يوم الولادة.',
    features: ['آمنة من يوم الولادة ١٠٠٪', 'مختبرة جلدياً بالكامل', 'بدون كحول أو بارابين', 'مدعمة بفيتامين E وD', '١٠٠ منديل كبير'],
    specs: { 'العدد': '١٠٠ منديل', 'العمر': 'من ٠ سنة', 'الاعتمادات': 'SFDA، Allergy UK' },
    isBestSeller: true, isFeatured: true,
  },
  {
    id: 25, slug: 'wipe-makeup-60',
    name: 'مناديل مزيل مكياج نَدى — ٦٠', nameEn: 'Makeup Remover 60',
    category: CAT('wet-wipes'), price: 26.99, comparePrice: 34.99,
    rating: 4.8, reviewCount: 534, stock: 380, sold: 8900, sku: 'ND-WW-003',
    badge: { label: 'للنساء', color: 'gold' },
    images: imgs(0), tags: ['مبللة', 'مكياج', 'نساء'],
    description: 'مناديل متخصصة لإزالة المكياج بلطف تام. تزيل أصعب ألوان المكياج الماء بدون تهيج. تحتوي على مستخلص الورد.',
    features: ['تزيل المكياج بلطف تام', 'مستخلص الورد الطبيعي', 'لا تهيج العيون', 'تنظيف عميق وترطيب', '٦٠ منديل كبير'],
    specs: { 'العدد': '٦٠ منديل', 'المكونات': 'ورد، ميسيلار واتر', 'آمن للعيون': 'نعم' },
  },
  {
    id: 26, slug: 'wipe-antibac-80',
    name: 'مناديل معقمة نَدى — ٨٠ منديل', nameEn: 'Antibacterial Wipes 80',
    category: CAT('wet-wipes'), price: 24.99, comparePrice: 31.99,
    rating: 4.7, reviewCount: 445, stock: 520, sold: 11200, sku: 'ND-WW-004',
    badge: { label: 'تعقيم فوري', color: 'green' },
    images: imgs(1), tags: ['مبللة', 'معقمة', 'بكتيريا'],
    description: 'مناديل معقمة بتركيبة قوية ضد البكتيريا والفيروسات. مثالية للرحلات والمستشفيات والسفر.',
    features: ['تقتل ٩٩.٩٪ البكتيريا', 'مضادة للفيروسات', 'فعالة ضد الانفلونزا', '٨٠ منديل', 'رائحة منعشة خفيفة'],
    specs: { 'الفعالية': '٩٩.٩٪', 'العدد': '٨٠ منديل', 'التعقيم': 'كحول ٧٠٪' },
  },
  {
    id: 27, slug: 'wipe-travel-30',
    name: 'مناديل سفر نَدى — ٣٠ منديل', nameEn: 'Travel Wipes 30',
    category: CAT('wet-wipes'), price: 12.99, comparePrice: 16.99,
    rating: 4.6, reviewCount: 289, stock: 700, sold: 7800, sku: 'ND-WW-005',
    badge: { label: 'للسفر', color: 'blue' },
    images: imgs(2), tags: ['مبللة', 'سفر', 'مدمج'],
    description: 'عبوة سفر مدمجة ٣٠ منديل. تدخل في حقيبة اليد بسهولة وتصحبك في كل رحلة.',
    features: ['عبوة مدمجة للسفر', '٣٠ منديل كبير', 'سهلة الحمل', 'بدون كحول', 'لكل أفراد العائلة'],
    specs: { 'العدد': '٣٠ منديل', 'الحجم': 'مدمج ١٥×١١ سم' },
  },
  {
    id: 28, slug: 'wipe-hand-sanitizer-50',
    name: 'مناديل معقم اليدين نَدى — ٥٠', nameEn: 'Hand Sanitizer Wipes 50',
    category: CAT('wet-wipes'), price: 17.99, comparePrice: 22.99,
    rating: 4.8, reviewCount: 534, stock: 680, sold: 13200, sku: 'ND-WW-006',
    badge: { label: 'ضروري', color: 'green' },
    images: imgs(3), tags: ['مبللة', 'معقم', 'يدين'],
    description: 'مناديل معقمة لليدين بتركيبة كحول ٧٠٪. تعقيم فوري بدون ماء. مرطبة لا تجفف اليدين.',
    features: ['كحول ٧٠٪ فعّال', 'تعقيم فوري في ثوانٍ', 'مرطبة لا تجفف', '٥٠ منديل', 'مثالية للسفر والعمل'],
    specs: { 'العدد': '٥٠ منديل', 'نسبة الكحول': '٧٠٪', 'المرطب': 'صبار وجليسرين' },
    isBestSeller: true,
  },
  {
    id: 29, slug: 'wipe-cooling-30',
    name: 'مناديل NOVI المنعشة — ٣٠ منديل', nameEn: 'Cooling Wipes 30',
    category: CAT('wet-wipes'), price: 16.99, comparePrice: 21.99,
    rating: 4.7, reviewCount: 198, stock: 420, sold: 5200, sku: 'ND-WW-007',
    badge: { label: 'صيفي', color: 'blue' },
    images: imgs(4), tags: ['مبللة', 'منعشة', 'صيف'],
    description: 'مناديل منعشة بتركيبة الأوكاليبتوس والنعناع. مثالية لصيف المملكة الحار. برودة فورية في أي مكان.',
    features: ['برودة فورية مضمونة', 'تركيبة أوكاليبتوس ونعناع', 'مثالية للصيف الحار', '٣٠ منديل كبير', 'منعشة للجسم والوجه'],
    specs: { 'العدد': '٣٠ منديل', 'المكونات': 'أوكاليبتوس، نعناع' },
    isNew: true,
  },
  {
    id: 30, slug: 'wipe-herbal-60',
    name: 'مناديل الأعشاب نَدى — ٦٠ منديل', nameEn: 'Herbal Wipes 60',
    category: CAT('wet-wipes'), price: 23.99, comparePrice: 29.99,
    rating: 4.7, reviewCount: 256, stock: 390, sold: 5400, sku: 'ND-WW-008',
    images: imgs(5), tags: ['مبللة', 'أعشاب', 'طبيعي'],
    description: 'مناديل مبللة بخلاصات الأعشاب الطبيعية: البابونج والحنظل والصبار. تجمع قوة الطبيعة في منديل واحد.',
    features: ['خلاصة بابونج طبيعية', 'خلاصة حنظل', 'صبار وزيت زيتون', '٦٠ منديل', 'للاستخدام اليومي'],
    specs: { 'العدد': '٦٠ منديل', 'المكونات': 'بابونج، حنظل، صبار' },
  },
  {
    id: 31, slug: 'wipe-sunscreen-30',
    name: 'مناديل واقي الشمس نَدى — ٣٠', nameEn: 'Sunscreen Wipes SPF30',
    category: CAT('wet-wipes'), price: 28.99, comparePrice: 36.99,
    rating: 4.7, reviewCount: 178, stock: 300, sold: 3800, sku: 'ND-WW-009',
    badge: { label: 'جديد', color: 'blue' },
    images: imgs(6), tags: ['مبللة', 'شمس', 'حماية'],
    description: 'مناديل مبللة مدمجة فيها واقي شمس SPF30. رفيقك الصيفي في كل مكان. حماية وترطيب في نفس الوقت.',
    features: ['واقي شمس SPF 30 مدمج', 'حماية من الأشعة UVA وUVB', '٣٠ منديل', 'خفيفة لا تدهن', 'مثالية للنشاط الخارجي'],
    specs: { 'SPF': '٣٠', 'العدد': '٣٠ منديل', 'الحماية': 'UVA وUVB' },
    isNew: true,
  },
  {
    id: 32, slug: 'wipe-face-clean-30',
    name: 'مناديل تنظيف الوجه نَدى — ٣٠', nameEn: 'Face Cleansing 30',
    category: CAT('wet-wipes'), price: 24.99, comparePrice: 31.99,
    rating: 4.8, reviewCount: 312, stock: 350, sold: 5800, sku: 'ND-WW-010',
    images: imgs(7), tags: ['مبللة', 'وجه', 'ميسيلار'],
    description: 'مناديل تنظيف وجه بتقنية الميسيلار المتطورة. تنظيف عميق يزيل الأوساخ والزهم والمكياج بلطف تام.',
    features: ['تقنية ميسيلار المتطورة', 'تنظيف عميق بلطف', 'لكل أنواع البشرة', 'ترطيب أثناء التنظيف', '٣٠ منديل'],
    specs: { 'العدد': '٣٠ منديل', 'التقنية': 'ميسيلار واتر' },
  },
  {
    id: 33, slug: 'wipe-body-25',
    name: 'مناديل جسم نَدى — ٢٥ منديل كبير', nameEn: 'Body Wipes 25',
    category: CAT('wet-wipes'), price: 21.99, comparePrice: 27.99,
    rating: 4.7, reviewCount: 234, stock: 340, sold: 4800, sku: 'ND-WW-011',
    images: imgs(0), tags: ['مبللة', 'جسم', 'رياضة'],
    description: 'مناديل جسم كبيرة الحجم لتنظيف شامل. مثالية بعد الرياضة الشديدة أو في السفر الطويل.',
    features: ['منديل كبير ٣٠×٢٢ سم', 'تنظيف كامل للجسم', 'رائحة منعشة مدوّمة', '٢٥ منديل', 'بدون كحول'],
    specs: { 'العدد': '٢٥ منديل', 'حجم المنديل': '٣٠×٢٢ سم' },
  },
  {
    id: 34, slug: 'wipe-multipack-5x80',
    name: 'بكج مبللة NOVI — ٥ × ٨٠ منديل', nameEn: 'Multipack 5x80',
    category: CAT('wet-wipes'), price: 79.99, comparePrice: 124.95,
    rating: 4.9, reviewCount: 445, stock: 250, sold: 8900, sku: 'ND-WW-012',
    badge: { label: 'وفّر ٣٦٪', color: 'red' },
    images: imgs(1), tags: ['مبللة', 'عبوة', 'توفير'],
    description: 'عبوة اقتصادية ضخمة ٥ عبوات × ٨٠ = ٤٠٠ منديل إجمالاً. التوفير الأمثل للعائلات.',
    features: ['٥ عبوات كاملة', 'إجمالي ٤٠٠ منديل', 'شحن مجاني', 'توفير ٤٥ ريال حقيقي', 'نفس جودة الكلاسيك'],
    specs: { 'العدد': '٥ عبوات', 'الإجمالي': '٤٠٠ منديل' },
  },
  {
    id: 35, slug: 'wipe-baby-3pack',
    name: 'بكج أطفال مبللة نَدى — ٣ × ١٠٠', nameEn: 'Baby 3-Pack',
    category: CAT('wet-wipes'), price: 57.99, comparePrice: 83.97,
    rating: 4.9, reviewCount: 389, stock: 220, sold: 7100, sku: 'ND-WW-013',
    badge: { label: 'وفّر ٣١٪', color: 'red' },
    images: imgs(2), tags: ['مبللة', 'أطفال', 'عبوة'],
    description: 'عبوة ثلاثية من مناديل الأطفال المبللة. ٣٠٠ منديل إجمالاً بسعر رائع. مثالية للأمهات المهتمات.',
    features: ['٣ عبوات × ١٠٠ منديل', 'إجمالي ٣٠٠ منديل', 'نفس الجودة الفائقة', 'شحن مجاني', 'توفير ٢٦ ريال'],
    specs: { 'العدد': '٣ عبوات', 'الإجمالي': '٣٠٠ منديل' },
  },
  {
    id: 36, slug: 'wipe-surface-50',
    name: 'مناديل تنظيف الأسطح نَدى — ٥٠', nameEn: 'Surface Cleaning 50',
    category: CAT('wet-wipes'), price: 14.99, comparePrice: 18.99,
    rating: 4.5, reviewCount: 167, stock: 600, sold: 6700, sku: 'ND-WW-014',
    images: imgs(3), tags: ['مبللة', 'تنظيف', 'أسطح'],
    description: 'مناديل مبللة لتنظيف الأسطح والأجهزة الإلكترونية. تنظف وتعقم دون خدش الأسطح.',
    features: ['آمنة على الشاشات', 'تنظيف وتعقيم معاً', '٥٠ منديل', 'رائحة ليمون منعشة', 'لا تترك آثاراً'],
    specs: { 'العدد': '٥٠ منديل', 'الاستخدام': 'أسطح وأجهزة إلكترونية' },
  },
  {
    id: 37, slug: 'wipe-intimate-20',
    name: 'مناديل عناية حميمة نَدى — ٢٠', nameEn: 'Intimate Care 20',
    category: CAT('wet-wipes'), price: 18.99, comparePrice: 23.99,
    rating: 4.8, reviewCount: 312, stock: 290, sold: 5600, sku: 'ND-WW-015',
    images: imgs(4), tags: ['مبللة', 'حميمة', 'عناية'],
    description: 'مناديل متخصصة للعناية الحميمة. تحافظ على الرقم الهيدروجيني الطبيعي. معتمدة طبياً للاستخدام اليومي.',
    features: ['معتمدة طبياً للعناية الحميمة', 'pH متوازن ٥.٥', 'بدون عطور قوية', 'خالية من الكحول', '٢٠ منديل سميك'],
    specs: { 'العدد': '٢٠ منديل', 'pH': '٥.٥ محايد', 'المكونات': 'لاكتيك آسيد، صبار' },
  },
  {
    id: 38, slug: 'wipe-deodorant-30',
    name: 'مناديل معطرة الجسم نَدى — ٣٠', nameEn: 'Deodorant Wipes 30',
    category: CAT('wet-wipes'), price: 19.99, comparePrice: 24.99,
    rating: 4.6, reviewCount: 189, stock: 430, sold: 4200, sku: 'ND-WW-016',
    images: imgs(5), tags: ['مبللة', 'معطر', 'عرق'],
    description: 'مناديل جسم معطرة تترك رائحة ناعمة تدوم ٨ ساعات. مثالية بعد النشاط الرياضي.',
    features: ['رائحة فواحة تدوم ٨ ساعات', 'تقليل التعرق', '٣٠ منديل كبير', 'آمن على البشرة', 'بدون كحول'],
    specs: { 'العدد': '٣٠ منديل', 'مدة الرائحة': 'حتى ٨ ساعات' },
  },

  /* ===================== COTTON TOWELS (12) ===================== */
  {
    id: 39, slug: 'towel-cotton-10',
    name: 'مناشف NOVI القطنية — ١٠ قطع', nameEn: 'Cotton Towels 10pk',
    category: CAT('cotton-towels'), price: 49.99, comparePrice: 64.99,
    rating: 4.7, reviewCount: 410, stock: 320, sold: 6800, sku: 'ND-CT-001',
    badge: { label: 'شائع', color: 'gold' },
    images: imgs(6), tags: ['مناشف', 'قطن', 'تنظيف'],
    description: 'مناشف تنظيف من الألياف القطنية قابلة لإعادة الاستخدام. تركيبة مضادة للبكتيريا. البديل الأمثل والاقتصادي لرولات الورق.',
    features: ['قابلة لإعادة الاستخدام ٥٠+ مرة', 'مضادة للبكتيريا طبيعياً', 'امتصاص فائق السرعة', 'قوية لا تنقطع', 'صديقة للبيئة'],
    specs: { 'العدد': '١٠ قطع', 'المادة': 'قطن ١٠٠٪', 'القياسات': '٣٠×٣٠ سم' },
    isBestSeller: true,
  },
  {
    id: 40, slug: 'towel-microfiber-10',
    name: 'مناشف NOVI مايكروفايبر — ١٠', nameEn: 'Microfiber Towels 10',
    category: CAT('cotton-towels'), price: 59.99, comparePrice: 74.99,
    rating: 4.8, reviewCount: 312, stock: 250, sold: 5200, sku: 'ND-CT-002',
    badge: { label: 'جديد', color: 'blue' },
    images: imgs(7), tags: ['مناشف', 'مايكروفايبر', 'امتصاص'],
    description: 'مناشف مايكروفايبر فائقة الامتصاص. تمتص ٧ أضعاف وزنها من الماء. لا تترك خطوطاً.',
    features: ['امتصاص ٧× الوزن', 'لا تترك خطوطاً', 'سريعة الجفاف', '١٠ قطع', 'ألوان متعددة'],
    specs: { 'العدد': '١٠ قطع', 'المادة': 'مايكروفايبر ٣٠٠ GSM' },
    isNew: true,
  },
  {
    id: 41, slug: 'towel-bamboo-5',
    name: 'مناشف NOVI بامبو — ٥ قطع', nameEn: 'Bamboo Towels 5pk',
    category: CAT('cotton-towels'), price: 69.99, comparePrice: 89.99,
    rating: 4.9, reviewCount: 189, stock: 150, sold: 2800, sku: 'ND-CT-003',
    badge: { label: 'صديق للبيئة', color: 'green' },
    images: imgs(0), tags: ['مناشف', 'بامبو', 'بيئة'],
    description: 'مناشف من ألياف الخيزران الطبيعية. أكثر نعومة ومتانة من القطن العادي. مضادة للبكتيريا طبيعياً.',
    features: ['خيزران طبيعي ١٠٠٪', 'أنعم من القطن', 'مضادة للبكتيريا', 'قابلة للتحلل', 'شهادة FSC'],
    specs: { 'العدد': '٥ قطع', 'المادة': 'ألياف خيزران طبيعية' },
  },
  {
    id: 42, slug: 'towel-colored-12',
    name: 'مناشف NOVI ملونة — ١٢ قطعة', nameEn: 'Colored Towels 12',
    category: CAT('cotton-towels'), price: 52.99, comparePrice: 67.99,
    rating: 4.6, reviewCount: 198, stock: 280, sold: 4500, sku: 'ND-CT-004',
    images: imgs(1), tags: ['مناشف', 'ملون', 'منظم'],
    description: 'مجموعة مناشف ملونة ١٢ قطعة. كل لون لغرض مختلف لتنظيم مثالي للمطبخ والحمام.',
    features: ['١٢ لوناً مختلفاً', 'كل لون لغرض محدد', 'تنظيم مثالي', 'سهلة التمييز', 'قطن عالي الجودة'],
    specs: { 'العدد': '١٢ قطعة', 'الألوان': '١٢ لون مختلف' },
  },
  {
    id: 43, slug: 'towel-organic-8',
    name: 'مناشف NOVI العضوية — ٨ قطع', nameEn: 'Organic Towels 8',
    category: CAT('cotton-towels'), price: 74.99, comparePrice: 94.99,
    rating: 4.8, reviewCount: 145, stock: 120, sold: 1900, sku: 'ND-CT-005',
    badge: { label: 'عضوي معتمد', color: 'green' },
    images: imgs(2), tags: ['مناشف', 'عضوي', 'طبيعي'],
    description: 'مناشف من قطن عضوي معتمد بدون مبيدات أو كيماويات. الخيار الأمثل للمهتمين بالبيئة وصحة العائلة.',
    features: ['قطن عضوي معتمد GOTS', 'بدون مبيدات أو كيماويات', '٨ قطع', 'تحلل طبيعي كامل', 'ألوان طبيعية'],
    specs: { 'العدد': '٨ قطع', 'الشهادة': 'GOTS Organic Certified' },
  },
  {
    id: 44, slug: 'towel-antibac-10',
    name: 'مناشف مضادة للبكتيريا نَدى — ١٠', nameEn: 'Antibac Towels 10',
    category: CAT('cotton-towels'), price: 64.99, comparePrice: 81.99,
    rating: 4.8, reviewCount: 267, stock: 200, sold: 4200, sku: 'ND-CT-006',
    badge: { label: 'حماية صحية', color: 'green' },
    images: imgs(3), tags: ['مناشف', 'بكتيريا', 'حماية'],
    description: 'مناشف قطنية بتركيبة نانو مضادة للبكتيريا والعفن. فعالة بعد ٥٠ غسلة. مثالية للمستشفيات والعيادات.',
    features: ['تقنية نانو مضادة للبكتيريا', 'مضادة للعفن والفطريات', 'فعالة بعد ٥٠ غسلة', '١٠ قطع', 'مثالية للعيادات'],
    specs: { 'العدد': '١٠ قطع', 'الفعالية': 'بعد ٥٠ غسلة كاملة' },
  },
  {
    id: 45, slug: 'towel-gym-3',
    name: 'مناشف جيم نَدى — ٣ قطع', nameEn: 'Gym Towels 3',
    category: CAT('cotton-towels'), price: 44.99, comparePrice: 56.99,
    rating: 4.7, reviewCount: 234, stock: 200, sold: 3800, sku: 'ND-CT-007',
    badge: { label: 'للرياضيين', color: 'blue' },
    images: imgs(4), tags: ['مناشف', 'جيم', 'رياضة'],
    description: 'مناشف رياضية للجيم. امتصاص سريع للعرق وجفاف في ١٥ دقيقة. تصاحبك في كل تمرين.',
    features: ['امتصاص سريع للعرق', 'جفاف في ١٥ دقيقة', 'بدون رائحة', '٣ قطع', 'خفيفة الوزن'],
    specs: { 'العدد': '٣ قطع', 'القياسات': '٣٠×١٠٠ سم' },
  },
  {
    id: 46, slug: 'towel-face-cotton-5',
    name: 'مناشف وجه نَدى القطنية — ٥', nameEn: 'Face Cotton Towels 5',
    category: CAT('cotton-towels'), price: 36.99, comparePrice: 46.99,
    rating: 4.7, reviewCount: 289, stock: 350, sold: 5600, sku: 'ND-CT-008',
    images: imgs(5), tags: ['مناشف', 'وجه', 'ناعم'],
    description: 'مناشف قطنية صغيرة خصيصاً للوجه. ناعمة جداً لا تهيج البشرة. مثالية بعد غسيل الوجه.',
    features: ['خصيصاً للوجه الحساس', 'ناعمة جداً', 'قطن مصري فاخر', '٥ قطع', 'قابلة للغسيل'],
    specs: { 'العدد': '٥ قطع', 'الحجم': '٢٠×٢٠ سم', 'المادة': 'قطن مصري' },
  },
  {
    id: 47, slug: 'towel-waffle-10',
    name: 'مناشف وافل نَدى — ١٠ قطع', nameEn: 'Waffle Towels 10',
    category: CAT('cotton-towels'), price: 44.99, comparePrice: 57.99,
    rating: 4.6, reviewCount: 178, stock: 320, sold: 3900, sku: 'ND-CT-009',
    images: imgs(6), tags: ['مناشف', 'وافل', 'خفيف'],
    description: 'مناشف وافل بنمط نسيج مميز ثلاثي الأبعاد. تنظيف فعال مع لمسة جمالية مختلفة.',
    features: ['نمط وافل مميز ثلاثي الأبعاد', 'تنظيف فعال', '١٠ قطع', 'خفيفة الوزن', 'جفاف سريع'],
    specs: { 'العدد': '١٠ قطع', 'النمط': 'وافل ثلاثي الأبعاد' },
  },
  {
    id: 48, slug: 'towel-heavy-5',
    name: 'مناشف ثقيلة نَدى — ٥ قطع صناعية', nameEn: 'Heavy Duty 5pk',
    category: CAT('cotton-towels'), price: 89.99, comparePrice: 114.99,
    rating: 4.9, reviewCount: 123, stock: 90, sold: 1600, sku: 'ND-CT-010',
    badge: { label: 'الأقوى', color: 'gold' },
    images: imgs(7), tags: ['مناشف', 'صناعي', 'ورشة'],
    description: 'مناشف صناعية ثقيلة الاستخدام للورش والمصانع. تتحمل أصعب أعمال التنظيف الصناعية.',
    features: ['استخدام صناعي شاق', 'تتحمل الزيوت والشحوم', '٥ قطع ضخمة', 'غسيل درجة ٩٠ مئوية', 'لا تتآكل أبداً'],
    specs: { 'العدد': '٥ قطع', 'الحجم': '٤٠×٤٠ سم', 'الوزن': '٤٠٠ جم/قطعة' },
  },
  {
    id: 49, slug: 'towel-cotton-20',
    name: 'مناشف NOVI القطنية — ٢٠ قطعة', nameEn: 'Cotton Towels 20pk',
    category: CAT('cotton-towels'), price: 84.99, comparePrice: 109.98,
    rating: 4.8, reviewCount: 267, stock: 180, sold: 4100, sku: 'ND-CT-011',
    badge: { label: 'وفّر ٢٣٪', color: 'red' },
    images: imgs(0), tags: ['مناشف', 'قطن', 'تجاري'],
    description: 'عبوة اقتصادية ٢٠ منشفة قطنية للمطابخ التجارية والمطاعم والفنادق.',
    features: ['٢٠ منشفة كاملة', 'قطن مصري فاخر', 'للمطابخ التجارية', 'تحمل الغسيل ٥٠+ مرة', 'مضادة للبكتيريا'],
    specs: { 'العدد': '٢٠ قطعة', 'المادة': 'قطن مصري عالي الجودة' },
  },
  {
    id: 50, slug: 'towel-multipurpose-15',
    name: 'مناشف متعددة الأغراض نَدى — ١٥', nameEn: 'Multipurpose 15pk',
    category: CAT('cotton-towels'), price: 54.99, comparePrice: 69.99,
    rating: 4.7, reviewCount: 234, stock: 280, sold: 4600, sku: 'ND-CT-012',
    images: imgs(1), tags: ['مناشف', 'متعدد', 'منزل'],
    description: 'مناشف متعددة الأغراض للمطبخ والحمام والسيارة. كل لون لغرض محدد.',
    features: ['متعددة الاستخدامات', '١٥ قطعة', 'ألوان مميزة لكل غرض', 'قوية ومتينة', 'سهلة التنظيف'],
    specs: { 'العدد': '١٥ قطعة', 'الألوان': 'أخضر/أحمر/أزرق' },
  },

  /* ===================== KITCHEN (10) ===================== */
  {
    id: 51, slug: 'kitchen-roll-3',
    name: 'رولات مطبخ NOVI — ٣ رولات', nameEn: 'Kitchen Roll 3-Pack',
    category: CAT('kitchen'), price: 34.99, comparePrice: 44.99,
    rating: 4.7, reviewCount: 520, stock: 450, sold: 9800, sku: 'ND-KT-001',
    badge: { label: 'الأكثر مبيعاً', color: 'gold' },
    images: imgs(2), tags: ['مطبخ', 'رول', 'امتصاص'],
    description: 'رولات مطبخ عالية الامتصاص. تنظف الأسطح والمتساقطات بكفاءة عالية. ٣ رولات في عبوة واحدة.',
    features: ['امتصاص فائق السرعة', 'تنظيف عميق بدون جهد', 'لا تترك ألياف', '٣ رولات في العبوة', 'للمطبخ التجاري'],
    specs: { 'العدد': '٣ رولات', 'ورقات/رول': '٥٠٠ ورقة' },
    isBestSeller: true,
  },
  {
    id: 52, slug: 'kitchen-roll-jumbo',
    name: 'رول مطبخ NOVI جامبو', nameEn: 'Jumbo Kitchen Roll',
    category: CAT('kitchen'), price: 24.99, comparePrice: 31.99,
    rating: 4.8, reviewCount: 198, stock: 380, sold: 5100, sku: 'ND-KT-002',
    badge: { label: 'الأكبر', color: 'gold' },
    images: imgs(3), tags: ['مطبخ', 'جامبو', 'ضخم'],
    description: 'رول مطبخ جامبو ضخم. يدوم ضعف الرولات العادية. مثالي للمطابخ الكبيرة والمطاعم.',
    features: ['ضعف الحجم العادي', '٨٠٠ ورقة كاملة', 'امتصاص مضاعف', 'ورق سميك قوي', 'قيمة ممتازة'],
    specs: { 'الورقات': '٨٠٠ ورقة', 'الحجم': 'جامبو ضخم' },
  },
  {
    id: 53, slug: 'kitchen-roll-5',
    name: 'رولات مطبخ NOVI — ٥ رولات', nameEn: 'Kitchen Roll 5-Pack',
    category: CAT('kitchen'), price: 54.99, comparePrice: 69.95,
    rating: 4.7, reviewCount: 345, stock: 300, sold: 7200, sku: 'ND-KT-003',
    badge: { label: 'وفّر ٢١٪', color: 'red' },
    images: imgs(4), tags: ['مطبخ', 'رول', 'توفير'],
    description: 'عبوة اقتصادية ٥ رولات مطبخ. توفير كبير مثالي لتخزين المطبخ الشهري.',
    features: ['٥ رولات كاملة', 'امتصاص فائق', 'لا تتمزق', 'مثالية للمطبخ التجاري', 'توفير ممتاز'],
    specs: { 'العدد': '٥ رولات', 'الإجمالي': '٢٥٠٠ ورقة' },
  },
  {
    id: 54, slug: 'kitchen-antibac-roll',
    name: 'رول مطبخ مضاد للبكتيريا نَدى', nameEn: 'Antibac Kitchen Roll',
    category: CAT('kitchen'), price: 19.99, comparePrice: 25.99,
    rating: 4.6, reviewCount: 289, stock: 550, sold: 6700, sku: 'ND-KT-004',
    images: imgs(5), tags: ['مطبخ', 'بكتيريا', 'تعقيم'],
    description: 'رول مطبخ بتركيبة نانو مضادة للبكتيريا. ينظف ويعقم في نفس الوقت. رائحة ليمون منعشة.',
    features: ['ينظف ويعقم معاً', 'تقنية نانو مضادة للبكتيريا', 'رائحة ليمون منعشة', 'ورقة واحدة تكفي', 'سريع الامتصاص'],
    specs: { 'الورقات': '٤٠٠ ورقة', 'العطر': 'ليمون طبيعي' },
  },
  {
    id: 55, slug: 'kitchen-towel-reusable',
    name: 'مناشف مطبخ نَدى قابلة للغسيل', nameEn: 'Reusable Kitchen Towels',
    category: CAT('kitchen'), price: 42.99, comparePrice: 54.99,
    rating: 4.8, reviewCount: 312, stock: 250, sold: 4900, sku: 'ND-KT-005',
    badge: { label: 'صديق للبيئة', color: 'green' },
    images: imgs(6), tags: ['مطبخ', 'قابل', 'غسيل'],
    description: 'مناشف مطبخ قطنية قابلة للغسيل والاستخدام ٥٠+ مرة. البديل البيئي الاقتصادي لرولات الورق.',
    features: ['قابلة للغسيل ٥٠+ مرة', 'توفر المال على المدى البعيد', 'صديقة للبيئة', 'قطن سميك ممتاز', '٣ قطع في العبوة'],
    specs: { 'العدد': '٣ قطع', 'الغسيل': 'حتى ٥٠+ مرة' },
  },
  {
    id: 56, slug: 'kitchen-wax-paper',
    name: 'ورق شمع مطبخ نَدى — ١٠ متر', nameEn: 'Wax Paper 10m',
    category: CAT('kitchen'), price: 18.99, comparePrice: 23.99,
    rating: 4.5, reviewCount: 145, stock: 420, sold: 3800, sku: 'ND-KT-006',
    images: imgs(7), tags: ['مطبخ', 'ورق', 'شمع'],
    description: 'ورق شمع مطبخ لف الطعام والخبز. غير لاصق وآمن للأغذية تماماً.',
    features: ['آمن على الأغذية ١٠٠٪', 'غير لاصق', 'للف الطعام والخبز', '١٠ متر', 'سهل القطع'],
    specs: { 'الطول': '١٠ متر', 'العرض': '٣٠ سم' },
  },
  {
    id: 57, slug: 'kitchen-foil-30',
    name: 'ورق ألومنيوم نَدى — ٣٠ متر', nameEn: 'Aluminum Foil 30m',
    category: CAT('kitchen'), price: 22.99, comparePrice: 28.99,
    rating: 4.6, reviewCount: 234, stock: 380, sold: 5800, sku: 'ND-KT-007',
    images: imgs(0), tags: ['مطبخ', 'ألومنيوم', 'فرن'],
    description: 'ورق ألومنيوم لف الطعام والطهي. مناسب للفرن والشواء. يحافظ على حرارة الطعام وطازجيته.',
    features: ['مناسب للفرن والشواء', 'يحافظ على الحرارة', '٣٠ متر', 'آمن للأغذية', 'مع علبة قاطعة'],
    specs: { 'الطول': '٣٠ متر', 'العرض': '٣٠ سم' },
  },
  {
    id: 58, slug: 'kitchen-cling-50',
    name: 'نايلون تغليف نَدى — ٥٠ متر', nameEn: 'Cling Wrap 50m',
    category: CAT('kitchen'), price: 16.99, comparePrice: 21.99,
    rating: 4.5, reviewCount: 178, stock: 450, sold: 6200, sku: 'ND-KT-008',
    images: imgs(1), tags: ['مطبخ', 'نايلون', 'ثلاجة'],
    description: 'نايلون تغليف شفاف للأطعمة. يحافظ على طازجية الطعام في الثلاجة والميكروويف.',
    features: ['يمدد بسهولة', '٥٠ متر', 'آمن للأغذية', 'شفاف ومريح', 'مناسب للميكرويف'],
    specs: { 'الطول': '٥٠ متر', 'العرض': '٢٩ سم' },
  },
  {
    id: 59, slug: 'kitchen-grease-100',
    name: 'ورق ماص للدهون نَدى — ١٠٠ ورقة', nameEn: 'Grease Absorb Paper 100',
    category: CAT('kitchen'), price: 28.99, comparePrice: 36.99,
    rating: 4.7, reviewCount: 189, stock: 300, sold: 4200, sku: 'ND-KT-009',
    images: imgs(2), tags: ['مطبخ', 'دهون', 'قلي'],
    description: 'ورق مطبخ خاص لامتصاص الدهون الزائدة من الطعام المقلي. يمتص الدهون دون أن يتمزق.',
    features: ['يمتص الدهون بكفاءة عالية', 'لا يتمزق تحت الحرارة', 'للأطعمة المقلية', 'بدون مواد كيميائية', '١٠٠ ورقة'],
    specs: { 'الاستخدام': 'امتصاص دهون', 'العدد': '١٠٠ ورقة' },
  },
  {
    id: 60, slug: 'kitchen-complete-set',
    name: 'طقم مطبخ NOVI الكامل', nameEn: 'Complete Kitchen Set',
    category: CAT('kitchen'), price: 79.99, comparePrice: 109.99,
    rating: 4.9, reviewCount: 145, stock: 120, sold: 2100, sku: 'ND-KT-010',
    badge: { label: 'طقم كامل', color: 'gold' },
    images: imgs(3), tags: ['مطبخ', 'طقم', 'شامل'],
    description: 'طقم مطبخ شامل: رول ورق + ورق شمع + ورق ألومنيوم + نايلون تغليف. كل ما تحتاجه.',
    features: ['٤ منتجات مطبخ شاملة', 'رول ورق + ورق شمع', 'ألومنيوم + نايلون', 'توفير ٣٠ ريال', 'في علبة تخزين جميلة'],
    specs: { 'المحتويات': 'رول + شمع + ألومنيوم + نايلون' },
    isFeatured: true,
  },

  /* ===================== POCKET TISSUE (10) ===================== */
  {
    id: 61, slug: 'pocket-classic-20',
    name: 'مناديل جيب نَدى كلاسيك — ٢٠ حزمة', nameEn: 'Pocket Classic 20pk',
    category: CAT('pocket'), price: 15.99, comparePrice: 19.99,
    rating: 4.6, reviewCount: 280, stock: 700, sold: 7800, sku: 'ND-PT-001',
    badge: { label: 'للسفر', color: 'blue' },
    images: imgs(4), tags: ['جيب', 'سفر', 'مدمج'],
    description: 'مناديل جيب مدمجة وعملية. ٢٠ حزمة × ١٠ مناديل = ٢٠٠ منديل. تدخل في كل حقيبة.',
    features: ['٢٠ حزمة مدمجة', '٢٠٠ منديل إجمالاً', 'مثالية للحمل والسفر', 'خفيفة ومريحة', 'بدون عطور'],
    specs: { 'العدد': '٢٠ حزمة × ١٠', 'الإجمالي': '٢٠٠ منديل' },
  },
  {
    id: 62, slug: 'pocket-aloe-20',
    name: 'مناديل جيب نَدى بالصبار — ٢٠', nameEn: 'Pocket Aloe 20',
    category: CAT('pocket'), price: 17.99, comparePrice: 22.99,
    rating: 4.7, reviewCount: 234, stock: 480, sold: 5900, sku: 'ND-PT-002',
    images: imgs(5), tags: ['جيب', 'صبار', 'ترطيب'],
    description: 'مناديل جيب مدعمة بالصبار. مرطبة وناعمة حتى بعد الاستخدام المتكرر.',
    features: ['صبار طبيعي مدعم', 'مرطبة للبشرة', '٢٠ حزمة', 'ناعمة جداً', 'للبشرة الحساسة'],
    specs: { 'العدد': '٢٠ حزمة', 'المكونات': 'صبار، فيتامين E' },
  },
  {
    id: 63, slug: 'pocket-kids-20',
    name: 'مناديل جيب أطفال نَدى — ٢٠', nameEn: 'Kids Pocket 20',
    category: CAT('pocket'), price: 14.99, comparePrice: 18.99,
    rating: 4.8, reviewCount: 312, stock: 550, sold: 7200, sku: 'ND-PT-003',
    badge: { label: 'للأطفال', color: 'gold' },
    images: imgs(6), tags: ['جيب', 'أطفال', 'كرتون'],
    description: 'مناديل جيب بشخصيات كرتونية محببة للأطفال. تشجعهم على استخدام المناديل دائماً.',
    features: ['شخصيات كرتونية', 'آمنة للأطفال ١٠٠٪', 'بدون كيماويات', 'ناعمة على بشرة الأطفال', '٢٠ حزمة'],
    specs: { 'العدد': '٢٠ حزمة', 'التصميم': 'شخصيات كرتونية' },
  },
  {
    id: 64, slug: 'pocket-box-50',
    name: 'مناديل جيب نَدى — علبة ٥٠ حزمة', nameEn: 'Pocket Box 50pk',
    category: CAT('pocket'), price: 34.99, comparePrice: 44.99,
    rating: 4.7, reviewCount: 198, stock: 350, sold: 4800, sku: 'ND-PT-004',
    badge: { label: 'وفّر ٢٢٪', color: 'red' },
    images: imgs(7), tags: ['جيب', 'جملة', 'توفير'],
    description: 'عبوة ضخمة ٥٠ حزمة مناديل جيب. توفير كبير مثالي للعائلات والمكاتب الكبيرة.',
    features: ['٥٠ حزمة كاملة', '٥٠٠ منديل إجمالاً', 'في علبة تخزين منظمة', 'توفير ١٠ ريال', 'مثالية للتوزيع'],
    specs: { 'العدد': '٥٠ حزمة', 'الإجمالي': '٥٠٠ منديل' },
  },
  {
    id: 65, slug: 'pocket-luxury-10',
    name: 'مناديل جيب نَدى فاخرة — ١٠ حزم', nameEn: 'Luxury Pocket 10',
    category: CAT('pocket'), price: 22.99, comparePrice: 28.99,
    rating: 4.8, reviewCount: 145, stock: 280, sold: 3200, sku: 'ND-PT-005',
    badge: { label: 'فاخر', color: 'gold' },
    images: imgs(0), tags: ['جيب', 'فاخر', 'هدية'],
    description: 'مناديل جيب فاخرة بغلاف جلدي أنيق. الرفيق المثالي في المناسبات والسفر الراقي.',
    features: ['غلاف جلدي فاخر', '١٠ حزم بـ٣ طبقات', 'مثالية للهدايا', 'تصميم حصري', 'ألوان متعددة'],
    specs: { 'العدد': '١٠ حزم', 'الغلاف': 'جلد طبيعي' },
  },
  {
    id: 66, slug: 'pocket-car-30',
    name: 'مناديل جيب نَدى للسيارة — ٣٠', nameEn: 'Car Pocket Tissues 30',
    category: CAT('pocket'), price: 21.99, comparePrice: 27.99,
    rating: 4.7, reviewCount: 289, stock: 480, sold: 6700, sku: 'ND-PT-006',
    badge: { label: 'للسيارة', color: 'blue' },
    images: imgs(1), tags: ['جيب', 'سيارة', 'مغناطيس'],
    description: 'مناديل جيب خاصة للسيارة مع حامل مغناطيسي. يثبت على لوحة التحكم بسهولة.',
    features: ['مع حامل مغناطيسي للسيارة', 'يثبت على لوحة التحكم', '٣٠ حزمة', 'إعادة التعبئة سهلة', 'تصميم أنيق'],
    specs: { 'العدد': '٣٠ حزمة', 'الإضافات': 'حامل مغناطيسي' },
  },
  {
    id: 67, slug: 'pocket-bamboo-20',
    name: 'مناديل جيب نَدى بامبو — ٢٠', nameEn: 'Bamboo Pocket 20',
    category: CAT('pocket'), price: 24.99, comparePrice: 31.99,
    rating: 4.7, reviewCount: 167, stock: 320, sold: 3800, sku: 'ND-PT-007',
    badge: { label: 'صديق للبيئة', color: 'green' },
    images: imgs(2), tags: ['جيب', 'بامبو', 'طبيعي'],
    description: 'مناديل جيب من ألياف الخيزران الطبيعية. أنعم وأقوى من الورق العادي.',
    features: ['ألياف خيزران طبيعية ١٠٠٪', 'أنعم من القطن', 'قابلة للتحلل', '٢٠ حزمة', 'بدون كيماويات'],
    specs: { 'العدد': '٢٠ حزمة', 'المادة': 'خيزران ١٠٠٪' },
  },
  {
    id: 68, slug: 'pocket-scented-15',
    name: 'مناديل جيب نَدى معطرة — ١٥', nameEn: 'Scented Pocket 15',
    category: CAT('pocket'), price: 14.99, comparePrice: 18.99,
    rating: 4.5, reviewCount: 189, stock: 560, sold: 5400, sku: 'ND-PT-008',
    images: imgs(3), tags: ['جيب', 'معطرة', 'مناسبة'],
    description: 'مناديل جيب معطرة برائحة الورد. رفيقك الأنيق في كل مناسبة وخروج.',
    features: ['رائحة ورد طبيعية', '١٥ حزمة', 'تصميم أنيق', 'مثالية للمناسبات', 'ألوان متعددة'],
    specs: { 'العدد': '١٥ حزمة', 'العطر': 'ورد طبيعي' },
  },
  {
    id: 69, slug: 'pocket-gym-15',
    name: 'مناديل جيب نَدى للرياضة — ١٥', nameEn: 'Sport Pocket 15',
    category: CAT('pocket'), price: 16.99, comparePrice: 20.99,
    rating: 4.6, reviewCount: 134, stock: 400, sold: 4100, sku: 'ND-PT-009',
    images: imgs(4), tags: ['جيب', 'رياضة', 'عرق'],
    description: 'مناديل جيب سميكة للرياضيين. قوية بما يكفي لتنظيف العرق الشديد.',
    features: ['سميكة وقوية', 'مثالية للعرق الشديد', 'بدون عطور', '١٥ حزمة', 'قياس كبير'],
    specs: { 'العدد': '١٥ حزمة', 'الاستخدام': 'رياضة ونشاط شديد' },
  },
  {
    id: 70, slug: 'pocket-antibac-20',
    name: 'مناديل جيب نَدى مضادة للبكتيريا — ٢٠', nameEn: 'Antibac Pocket 20',
    category: CAT('pocket'), price: 19.99, comparePrice: 24.99,
    rating: 4.7, reviewCount: 178, stock: 430, sold: 5200, sku: 'ND-PT-010',
    badge: { label: 'تعقيم خفيف', color: 'green' },
    images: imgs(5), tags: ['جيب', 'معقمة', 'بكتيريا'],
    description: 'مناديل جيب جافة بتركيبة مضادة للبكتيريا. تنظيف وتعقيم خفيف في كل وقت.',
    features: ['مضادة للبكتيريا', '٢٠ حزمة', 'تنظيف خفيف مستمر', 'للاستخدام اليومي', 'بدون كحول'],
    specs: { 'العدد': '٢٠ حزمة', 'الفعالية': 'مضادة للبكتيريا' },
  },

  /* ===================== SPECIALTY (5) ===================== */
  {
    id: 71, slug: 'spec-makeup-sponge-10',
    name: 'إسفنجات ترتيب مكياج نَدى — ١٠', nameEn: 'Makeup Sponges 10',
    category: CAT('specialty'), price: 34.99, comparePrice: 44.99,
    rating: 4.8, reviewCount: 312, stock: 200, sold: 4800, sku: 'ND-SP-001',
    badge: { label: 'جديد', color: 'blue' },
    images: imgs(6), tags: ['خاص', 'مكياج', 'نساء'],
    description: 'إسفنجات تطبيق المكياج الاحترافية. ناعمة ولطيفة على البشرة. تطبيق متساوٍ بدون خطوط.',
    features: ['تطبيق متساوٍ بدون خطوط', 'ناعمة على البشرة', 'قابلة للغسيل', '١٠ قطع', 'احترافية للمكياج'],
    specs: { 'العدد': '١٠ قطع', 'المادة': 'إسفنج طبي ناعم' },
    isNew: true,
  },
  {
    id: 72, slug: 'spec-cotton-pads-100',
    name: 'قطن ديسك نَدى — ١٠٠ قرص', nameEn: 'Cotton Pads 100',
    category: CAT('specialty'), price: 16.99, comparePrice: 21.99,
    rating: 4.7, reviewCount: 445, stock: 600, sold: 8900, sku: 'ND-SP-002',
    badge: { label: 'شائع', color: 'gold' },
    images: imgs(7), tags: ['خاص', 'قطن', 'مكياج'],
    description: 'أقراص قطن طبيعية ناعمة ١٠٠٪ لإزالة المكياج والعناية بالبشرة.',
    features: ['قطن طبيعي ١٠٠٪', 'ناعمة جداً على البشرة', '١٠٠ قرص', 'بدون نسالة', 'للمكياج والعناية'],
    specs: { 'العدد': '١٠٠ قرص', 'المادة': 'قطن طبيعي ١٠٠٪' },
    isBestSeller: true,
  },
  {
    id: 73, slug: 'spec-cotton-buds-200',
    name: 'أعواد قطن نَدى — ٢٠٠ عود', nameEn: 'Cotton Buds 200',
    category: CAT('specialty'), price: 12.99, comparePrice: 16.99,
    rating: 4.6, reviewCount: 389, stock: 800, sold: 11200, sku: 'ND-SP-003',
    images: imgs(0), tags: ['خاص', 'أعواد', 'آذان'],
    description: 'أعواد قطن ناعمة ومتينة للعناية بالأذنين والتجميل والفنون.',
    features: ['قطن ناعم ١٠٠٪', '٢٠٠ عود في العبوة', 'للأذنين والتجميل', 'عصا بلاستيكية أو ورقية', 'متينة لا تتكسر'],
    specs: { 'العدد': '٢٠٠ عود', 'المادة': 'قطن + عصا آمنة' },
  },
  {
    id: 74, slug: 'spec-facial-mask-10',
    name: 'أقنعة وجه نَدى — ١٠ قطع', nameEn: 'Facial Sheet Masks 10',
    category: CAT('specialty'), price: 49.99, comparePrice: 64.99,
    rating: 4.8, reviewCount: 234, stock: 180, sold: 3200, sku: 'ND-SP-004',
    badge: { label: 'جديد', color: 'blue' },
    images: imgs(1), tags: ['خاص', 'قناع', 'بشرة'],
    description: 'أقنعة ورقية للوجه بخلاصات طبيعية. ترطيب عميق وتغذية فائقة للبشرة.',
    features: ['ورقة مشبعة بالسيروم', '١٠ قطع متنوعة', 'صبار + فيتامين C + الكولاجين', 'ترطيب عميق', 'مناسبة لكل أنواع البشرة'],
    specs: { 'العدد': '١٠ قطع', 'الأنواع': 'صبار، فيتامين C، كولاجين' },
    isNew: true,
  },
  {
    id: 75, slug: 'spec-eye-patches-20',
    name: 'لصقات تحت العين نَدى — ٢٠ زوج', nameEn: 'Eye Patches 20pr',
    category: CAT('specialty'), price: 54.99, comparePrice: 69.99,
    rating: 4.7, reviewCount: 178, stock: 150, sold: 2800, sku: 'ND-SP-005',
    badge: { label: 'عناية فائقة', color: 'gold' },
    images: imgs(2), tags: ['خاص', 'عين', 'عناية'],
    description: 'لصقات هيدروجيل تحت العين لتفتيح الهالات وتقليل الانتفاخ. نتيجة ملحوظة من الاستخدام الأول.',
    features: ['تفتيح الهالات الداكنة', 'تقليل الانتفاخ', 'هيدروجيل فائق الترطيب', '٢٠ زوج', 'نتيجة من أول استخدام'],
    specs: { 'العدد': '٢٠ زوج', 'المادة': 'هيدروجيل' },
  },

  /* ===================== BUNDLES (5) ===================== */
  {
    id: 76, slug: 'bundle-6x-classic',
    name: 'بكج NOVI التوفير — ٦ علب كلاسيك', nameEn: 'Bundle 6x Classic',
    category: CAT('bundles'), price: 149.99, comparePrice: 239.94,
    rating: 4.9, reviewCount: 890, stock: 200, sold: 12800, sku: 'ND-BD-001',
    badge: { label: 'وفّر ٣٧٪', color: 'red' },
    images: imgs(3), tags: ['بكج', 'توفير', 'عائلة'],
    description: 'أفضل قيمة! ٦ علب من مناديل NOVI كلاسيك ٦٠٠ منديل. إجمالي ٣٦٠٠ منديل. شحن مجاني. توفير ٩٠ ريال حقيقي.',
    features: ['٦ علب كلاسيك كاملة', 'إجمالي ٣٦٠٠ منديل', 'شحن مجاني مضمون', 'توفير ٩٠ ريال', 'خليط وردي وأخضر'],
    specs: { 'العدد': '٦ علب', 'الإجمالي': '٣٦٠٠ منديل', 'الشحن': 'مجاني' },
    isBestSeller: true, isFeatured: true,
  },
  {
    id: 77, slug: 'bundle-12x-mega',
    name: 'بكج NOVI ميجا — ١٢ علبة', nameEn: 'Mega Bundle 12x',
    category: CAT('bundles'), price: 269.99, comparePrice: 479.88,
    rating: 4.8, reviewCount: 340, stock: 100, sold: 5800, sku: 'ND-BD-002',
    badge: { label: 'وفّر ٤٤٪', color: 'red' },
    images: imgs(4), tags: ['بكج', 'ميجا', 'ضخم'],
    description: 'الباقة العائلية الضخمة! ١٢ علبة كلاسيك فاخرة. أكبر توفير. شحن مجاني وتغليف مميز.',
    features: ['١٢ علبة كاملة', 'إجمالي ٧٢٠٠ منديل', 'توفير ٢١٠ ريال', 'توصيل سريع مجاني', 'نقاط ولاء مضاعفة'],
    specs: { 'العدد': '١٢ علبة', 'الإجمالي': '٧٢٠٠ منديل' },
    isFeatured: true,
  },
  {
    id: 78, slug: 'bundle-wipes-family',
    name: 'بكج عائلة المبللة — ٥ عبوات متنوعة', nameEn: 'Wipes Family Bundle',
    category: CAT('bundles'), price: 89.99, comparePrice: 124.95,
    rating: 4.8, reviewCount: 445, stock: 220, sold: 7100, sku: 'ND-BD-003',
    badge: { label: 'وفّر ٢٨٪', color: 'red' },
    images: imgs(5), tags: ['بكج', 'مبللة', 'عائلة'],
    description: '٥ عبوات مبللة متنوعة: كلاسيك + أطفال + معقمة + سفر + جسم. مثالي للعائلة الكاملة.',
    features: ['٥ عبوات متنوعة', 'أطفال + بالغين', 'معقمة + صبار', 'إجمالي ٣٨٠ منديل', 'شحن مجاني'],
    specs: { 'العدد': '٥ عبوات', 'الأنواع': 'كلاسيك، أطفال، معقمة، سفر، جسم' },
  },
  {
    id: 79, slug: 'bundle-home-complete',
    name: 'بكج المنزل الشامل — ١٠ منتجات', nameEn: 'Home Complete Bundle',
    category: CAT('bundles'), price: 199.99, comparePrice: 299.99,
    rating: 4.9, reviewCount: 234, stock: 80, sold: 3200, sku: 'ND-BD-004',
    badge: { label: 'الأشمل', color: 'gold' },
    images: imgs(6), tags: ['بكج', 'منزل', 'شامل'],
    description: 'بكج المنزل الشامل! كل ما يحتاجه منزلك: مناديل وجه + مبللة + مناشف + رول مطبخ.',
    features: ['٤ علب مناديل وجه', '٢ عبوة مبللة', '١ مناشف قطنية', '١ رول مطبخ', 'توفير ١٠٠ ريال + شحن مجاني'],
    specs: { 'العناصر': '١٠ منتجات متنوعة' },
    isFeatured: true,
  },
  {
    id: 80, slug: 'bundle-gift-luxury',
    name: 'بكج الهدايا الفاخرة — صندوق مميز', nameEn: 'Luxury Gift Bundle',
    category: CAT('bundles'), price: 179.99, comparePrice: 249.99,
    rating: 4.9, reviewCount: 167, stock: 60, sold: 2100, sku: 'ND-BD-005',
    badge: { label: 'هدية مثالية', color: 'gold' },
    images: imgs(7), tags: ['بكج', 'هدايا', 'فاخر'],
    description: 'صندوق هدايا فاخر يشمل أفضل منتجات NOVI. التغليف المميز يجعله الهدية المثالية لأي مناسبة.',
    features: ['صندوق هدايا أنيق', '٦ منتجات فاخرة مختارة', 'تغليف هدايا مجاني', 'بطاقة تهنئة', 'توصيل معبأ بعناية'],
    specs: { 'العناصر': '٦ منتجات فاخرة', 'التغليف': 'هدايا بصندوق أنيق' },
  },
]

export default PRODUCTS
